### ISSUE TITLE
Ubuntu-Frame-VNC service down

### ISSUE THREAD

**Issue by nawip** [canonical/ubuntu-frame-vnc#24]
I get an error when implementing remote access via ubuntu-frame-vnc... help me figure it out

ERROR: ../src/src/main.c: 408: Virtual Pointer protocol not supported by compositor.
ERROR: ../src/src/main.c: 409: wayvnc may still work if started with --disable-input.
ERROR: ../src/src/main.c: 1391: Failed to initialise wayland

OS: Armbian (24.8.0-trunk.399) aarch64 
Host: OrangePi 3 LTS 
Kernel: 6.6.36-current-sunxi64 
Packages: 1404 (dpkg), 7 (snap) 
Shell: bash 5.2.21 
Resolution: 1024x600 
Terminal: /dev/pts/0 
CPU: (4) @ 1.800GHz 
Memory: 711MiB / 1923MiB 

used tutorial: https://mir-server.io/docs/how-to-use-remote-assistance-with-ubuntu-frame

but it work on virtual

**Comment by AlanGriffiths** [comment]
Hi @nawip,

the problem you are seeing likely stems from the AppArmor support on the host OS not being what is needed.

On thing you can try is to add `authorise-without-apparmor=true` to Ubuntu Frame's `config` option (see https://mir-server.io/docs/ubuntu-frame-configuration-options).

If that doesn't work, it is the Frame logs from the connection attempt that will be relevant to diagnosing the problem.

**Comment by nawip** [comment]
Thanks Alan!!! it is wonderful!!! IT WORKED
