### ISSUE TITLE
How to use remmina to connect Ubuntu-Frame-VNC?

### ISSUE THREAD

**Issue by nawip** [canonical/ubuntu-frame-vnc#25]
Remmina not connected...
But https://discourse.ubuntu.com/t/how-to-use-remote-assistance-with-ubuntu-frame/29667#heading--client-compatibility - tested

**Comment by Saviq** [comment]
I'm going to put this down to this:

> Rather than expose an extra attack surface, ubuntu-frame-vnc is configured to only listen on localhost, on port 5900 (the default VNC port). It is up to the operator to expose it securely to the outside or provide other means of access.
> 
> SSH port forwarding is a common approach. On your host, issue:
> 
>    $ ssh -L 5900:localhost:5900 <user>@<hostname>
> 
> You will then be able to connect to localhost with any VNC client running on your host.

**Comment by nawip** [comment]
host work on wayland
nothing ((

**Comment by Saviq** [comment]
Sorry, we can't do anything with so little details. You'll have to say what and how you're attempting, what doesn't work.

**Comment by nawip** [comment]
I have installed ubuntu-frame-vnc on ubuntu server. I did everything according to the tutorial https://discourse.ubuntu.com/t/how-to-use-remote-assistance-with-ubuntu-frame/29667#heading--client-compatibility. I connect to ubuntu-frame vnc via frame-it.vnc, but other clients do not connect.

**Comment by AlanGriffiths** [comment]
> I connect to ubuntu-frame vnc via frame-it.vnc, but other clients do not conneted.

`frame-it.vnc` is not a VNC client. It is a script to set up SSH port forwarding and then call a VNC client (by default gvncviewer):

```
$ cat /snap/frame-it/current/frame-it-vnc 
#!/bin/sh
set -eu

vnc_viewer="$(snapctl get vnc-viewer)"
vnc_display="$(snapctl get vnc-display)"

# We `sleep 3` as a hack so that ssh will tidy up after use. It gives
# time for the viewer to grab the tunnel and hold the connection open.
# The alternative `-N` would leave the tunnel open.
ssh -T -L "59${vnc_display:-00}:localhost:5900" -f "$@" "sleep 3"
"${vnc_viewer:-gvncviewer}" "localhost:${vnc_display:-00}"
``

You can either set up port forwarding yourself or configure `frame-it.vnc` to use another client:

    snap set vnc_viewer=remmina
